### ISSUE TITLE
Can't read mzXML containing multiple msRun elements

### ISSUE THREAD

**Issue by ypriverol** [PRIDE-Utilities/jmzReader#2]
Dear jmzreader developers,

I had five mzXML files that I merged using MzxmlMerge tool (http://proteotools2.pharmacy.arizona.edu/proteotools/mzxmlmerge.jsp).

As far as I Known, the generated mzXML file is correct but when I load it with MzXMLfile:

File mzxmlFile = new File("merged.mzXML");

I got the following error stack (I have attached the file so that you can have a look at it):

2015-03-23 11:17:08,754 DEBUG XmlXpathIndexer - Indexing and keeping track of line numbers.
2015-03-23 11:17:08,891 ERROR XmlXpathIndexer - Tag name mismatch! Found 'mzXML' but 'msRun' on stack.
 State of the Stack:
[mzXML at line 2]
[msRun at line 3]
[msRun at line 20]
[msRun at line 37]

Tag name mismatch! Found 'mzXML' but 'msRun' on stack.
 State of the Stack:
[mzXML at line 2]
[msRun at line 3]
[msRun at line 20]
[msRun at line 37]

line number88

I hope you can help me. With best regards.

Regards,

Hugo.

PD: File url [https://jmzreader.googlecode.com/issues/attachment?aid=70000000&name=merged.mzXML&token=ABZ6GAf15uNKA6ZhIqZBg8Huwl5n1vvBCg%3A1432812267846&id=7&mod_ts_token=ABZ6GAcs3Nv4g0jURsrz0q5xw69GFBVjWQ%3A1432812267846]

**Comment by ppedrioli** [comment]
Dear Hugo,

Not sure if I understand your situation correctly, since the link to the file is no longer active.
However, according the schema, there must be one, but only one, msRun element in an mzXML file.
The element is defined as:

`<xs:element name="msRun"> `

in the schema without specifying minOccurs or maxOccurs (both of which are 1 by default). Therefore an mzXML file with more then one msRun element would not be valid.

Cheers,

Patrick
